version: 0.14.5-{branch}-{build}

environment:
    global:
        RUST_BACKTRACE: full
        RUST_TEST_THREADS: 1
    matrix:
        - channel: stable
          target: x86_64-pc-windows-msvc
          filename: ctehxk2-x64.dll
        - channel: stable
          target: i686-pc-windows-msvc
          filename: ctehxk2-x86.dll

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %target% --default-toolchain %channel%
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -vV
    - cargo -vV

cache:
    - '%USERPROFILE%\.cargo'

build: off

build_script: cargo build

test_script:
    - cargo test --verbose --all -- --nocapture
    - cd examples/settings-file
    - cargo test --verbose --all -- --nocapture
    - cd ../../
    - cd examples/use-library
    - cargo test --verbose --all -- --nocapture
    - cd ../../

after_test:
    - cargo build --release --verbose
    - ren target\release\ctehxk2.dll %filename%

artifacts:
    - path: 'target/release/*.dll'
    - path: 'target/release/*.h'

deploy:
    description: ''
    auth_token:
        secure: VeDpNYDNNJvMfdBEgizkRlB/Goejuq3IVt5ltSJ48ZVGJpvxBNEApjHAvTuCsNAk
    provider: GitHub
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
