dist: trusty
language: rust
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/target
before_script:
  - cargo install rustfmt --force
  - nvm install node
  - npm install
script:
  - npm run test
  - cargo build --release
deploy:
  provider: releases
  api_key:
    secure: "0PjWY+wqGzyjKofsdBIG4+fDBrpCZNzOLsQbpvBOvwYOBakEFIFbQPdjU39Smam5pxme0zcZjH5yPpHE34leJLCom1S4SbwgJhMEmAM0EX/6nnTv2l8wBtS9d16JeH
bIzjeIlDcNMtQaGbV7a/Ft/81My1KYhNZrC4IzQf2JL4teg1G2CBBGaAoginUPRFgDR3L42XeDeiIP3YA4E4BdTG7Vggh0p2P0a/CrFelpfnYIYKvuWzic+FKJ78HuMEFFhMuiLh3
mB5nOrT3p5mj1PB2UA3BhPemaDb7gyv3mvZLPy/sxyS2SuBkCKKwCYOSbMG8rxGZLlkrpfLFFW3m4cVNC82B4dk4yAxQYUOzdZeYcjeZFEEpgYgRHHdWZRcAMb/HXjvDJIfBwZghx
9bIts/kjsr9ebtwwSZdAdZdHoJ7vYHBNxLG1q0Mpx+vNez1H2/vO0WqAwHmZjylkWUv/euOh1Fb6stCiHfYZTZDuPTh1pAiThMbIQs/US6lL7uWs1lA1LJ+xSnLCXnkyllw4v+l5K
q+Ufqx4UQYlz4ANsfq1336Bf1eIYmXiOCaSTem9zRM8bcapdWPjT7cLsbHHKgZsQBlstbQnK3QjPbH+xSvRvE5ktMGxsY3FVTgPa1lTGg1v1yea4Hu/8qpNGYuYCSVE0agNJ2NEZM
g5dXSMPiA="
  file:
    - path: target/release/libctehxk2.so
      name: libctehxk2.so
    - path: target/release/ctehxk2.h
      name: ctehxk2.h
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
