language: rust
env:
    global:
        - RUST_BACKTRACE=full
        - RUST_TEST_THREADS=1
matrix:
    fast_finish: true
    include:
        - os: linux
          rust: nightly
          env: DEPLOY_FILE=target/release/libctehxk2.so
        - os: osx
          rust: nightly
          env: DEPLOY_FILE=target/release/libctehxk2.dylib
cache: cargo
before_script:
    # work-around for travis-ci/travis-ci#6307
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            command curl -sSL https://rvm.io/mpapis.asc | gpg --import -;
            rvm get stable;
            ulimit -n 2048;
        fi
    - rustup component add rustfmt-preview
script:
    - cargo fmt --all -- --check
    - cargo test --verbose --all -- --nocapture
    - cargo build --verbose
    - cd examples/settings-file
    - cargo fmt --all -- --check
    - cargo test --verbose --all -- --nocapture
    - cd ../../
    - cd examples/use-library
    - cargo fmt --all -- --check
    - cargo test --verbose --all -- --nocapture
    - cd ../../
before_deploy:
    - cargo build --release --verbose
deploy:
    provider: releases
    api_key: ${API_KEY}
    file_glob: true
    file: "$DEPLOY_FILE"
    skip_cleanup: true
    on:
        tags: true
notifications:
    email: false
