dist: trusty
language: rust
cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/node_modules
  - $TRAVIS_BUILD_DIR/target
before_script:
- cargo install rustfmt --force
- nvm install node
- npm install
script:
- npm run test
- cargo build --release
deploy:
  provider: releases
  api-key:
    secure: a2AuuC5bFwG5HyHFii/6oAoX6HjiOLtjnNjC1pJLBPGNVb0HS9m543MXEWstSfGZpyNBN5eAOcBwOM0AWv+J9KSKQBzqM3OnhZNyZXiPv26sy+mrjAvTkOgvP77VsoOB0nLS+x6ViP0Ly6HbLBXDAiCgN3q+bMlmmWeYMrqPdemzVlGN8bEqSexYTTn3mgpPoTpX1FS3/aQbYxP3e3TT0GoEydKjDqW2HZbzO7uNWOim1/W5+aPj+hDjpYAhurIzktkgkVGFSUsNlY0xaf/MUo3VeOE4M5ITBhWgXltgA9YltAEKu8KMlQ+dIP696c8dkc+QGJdziPz33ExAkvLWpnmSWqjHp+VZlEAG7ZYS/JJOzJl7zdfFMGHu52uDI4cmjbDISu+pOLhn3V1jynuN+42nOe0ZqOFLbrd/OtW+/DHtPF1hxxYnMHaEge0j25T6lRKtb0+9Vo+tu4rvAMc0OeZgcxwA7PKLjmq5CsRSOOAeRTX4dUEt9q/xdMdCIDdc7rwtSRVwoQSTk0o4nZOq+ebrz7SKy/Mx7i8x9JMHziaca2q0sNdhiGnJqq+y3WoDNsADhYO6+MTnwfZtYdjadfd2bQeNi8my+Bj+aX4sWo6yzWTCjX/OeZTZlecxHcoWUa2mE6J1bzrT1eNSKjUukEEdqoCoAVFKPxZb88Sng80=
  file:
  - path: target/release/libctehxk2.so
    name: libctehxk2.so
  - path: target/release/ctehxk2.h
    name: ctehxk2.h
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
