dist: trusty
language: rust
rust:
    - stable
cache: cargo
before_script:
    - cargo install rustfmt --force
script:
    - cargo test --verbose --all -- --test-threads=1
    - cargo build --release --verbose
deploy:
    provider: releases
    api_key: ${API_KEY}
    file:
        - "target/release/libctehxk2.so"
        - "target/release/ctehxk2.h"
    skip_cleanup: true
    on:
        tags: true
notifications:
    email: false
