[package]
name = "k2_basecamp"
version = "0.3.0"
authors = ["Christian Fochler <fochler@ehealhtexperts.de>"]
publish = false

[dependencies]
hyper = "0.10"
lazy_static = "0.2"
libc = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[lib]
name = "k2_basecamp"
crate-type = ["cdylib"]

[target.x86_64-pc-windows-msvc.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.i686-pc-windows-msvc.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.i686-pc-windows-gnu.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"