[package]
name = "k2_basecamp"
version = "0.14.6"
description = "CTAPI adpater for the gematik Konnektor"
authors = ["Christian Fochler <fochler@ehealhtexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-basecamp.git"
publish = false
build = "build.rs"

[lib]
name = "ctehxk2"
crate-type = ["cdylib"]

[dependencies]
antidote = "1.0.0"
base64 = "0.9.0"
futures = "0.1.17"
hyper = "0.11.9"
lazy_static = "1.0.0"
log = "0.4.0"
log4rs = "0.8.0"
serde = "1.0.25"
serde_derive = "1.0.25"
serde_json = "1.0.8"
tokio-core = "0.1.11"

[dependencies.config]
git = "https://github.com/ChriFo/config-rs"
branch = "fix/env"
default-features = false
features = ["json", "toml", "yaml"]

[build-dependencies]
moz-cheddar = "0.4.2"

[dev-dependencies]
rand = "0.4.1"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "v0.1.1" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.4"

[package.metadata.winres]
FileDescription = "K2 adapter for CTAPI"
FileVersion = "0.14.6"
LegalCopyright = "eHealthExperts GmbH. All rights reserved."
OriginalFilename = "ctehxk2.dll"
ProductName = "K2 basecamp"
ProductVersion = "0.14.6"

[package.metadata.release]
sign-commit = true
disable-push = true
upload-doc = false
no-dev-version = true
tag-message = "{{version}}"
tag-prefix = "v"
pre-release-commit-message = "{{version}}"
pre-release-replacements = [
    {file=".appveyor.yml", search="version: [a-z0-9\\.\\-\\{\\}]+", replace="version: {{version}}-{branch}-{build}"},
    {file="Cargo.toml", search="version = \"[0-9\\.]+\"", replace="version = \"{{version}}\""},
    {file="Cargo.toml", search="FileVersion = \"[0-9\\.]+\"", replace="FileVersion = \"{{version}}\""},
    {file="Cargo.toml", search="ProductVersion = \"[0-9\\.]+\"", replace="ProductVersion = \"{{version}}\""},
]
