[package]
name = "k2_basecamp"
version = "0.15.5"
description = "CTAPI adpater for the gematik Konnektor"
authors = ["Christian Fochler <fochler@ehealhtexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-basecamp.git"
publish = false
build = "build.rs"

[lib]
name = "ctehxk2"
crate-type = ["cdylib"]

[dependencies]
antidote = "1.0.0"
data-encoding = "2.1.2"
lazy_static = "1.3.0"
log = "0.4.6"
log4rs = { git = "https://github.com/sfackler/log4rs" }
reqwest = "0.9.11"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"

[dependencies.config]
version = "0.9.2"
default-features = false
features = ["json", "toml", "yaml"]

[build-dependencies]
moz-cheddar = "0.4.2"

[dev-dependencies]
rand = "0.6.5"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "v0.5.4" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.8"

[package.metadata.winres]
FileDescription = "K2 adapter for CTAPI"
FileVersion = "0.15.5"
LegalCopyright = "eHealth Experts GmbH. All rights reserved."
OriginalFilename = "ctehxk2.dll"
ProductName = "K2 basecamp"
ProductVersion = "0.15.5"
