[package]
name = "ctehxk2"
version = "0.15.9"
description = "CTAPI adpater for the gematik Konnektor"
authors = ["Christian Fochler <fochler@ehealhtexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-basecamp.git"
publish = false
build = "build.rs"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
antidote = "1.0.0"
chrono = "0.4.11"
data-encoding = "2.2.0"
failure = "0.1.7"
fern = "0.6.0"
lazy_static = "1.4.0"
log = "0.4.8"
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.52"
ureq = { version = "0.12.1", features = ["json"] }
url = "2.1.1"

[dependencies.config]
version = "0.10.1"
default-features = false
features = ["ini", "json", "yaml"]

[dev-dependencies]
const-cstr = "0.3.0"
dlopen = "0.1.8"
futures-timer = "3.0.2"
rand = "0.7.3"
serial_test = "0.4.0"
spectral = "0.6.0"
tempfile = "3.1.0"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "0.8.0" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[package.metadata.winres]
FileDescription = "K2 adapter for CTAPI"
FileVersion = "0.15.9"
LegalCopyright = "eHealth Experts GmbH. All rights reserved."
OriginalFilename = "ctehxk2.dll"
ProductName = "K2 basecamp"
ProductVersion = "0.15.9"
