[package]
name = "k2_basecamp"
version = "0.7.1"
authors = ["Christian Fochler <fochler@ehealhtexperts.de>"]
repository = "http://stash.ehex.de/scm/k2/k2-basecamp.git"
publish = false
build = "build.rs"

[lib]
name = "ctehxk2"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.5"
envy = "0.2"
hyper = "0.10"
lazy_static = "0.2"
log = "0.3"
log4rs = "0.7"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[build-dependencies]
rusty-cheddar = "0.3"

[dev-dependencies]
http_stub = "0.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
CompanyName = "eHealthExperts GmbH"
FileDescription = "K2 adapter for CTAPI"
FileVersion = "0.7.1"
LegalCopyright = "All rights reserved."
OriginalFilename = "ctehxk2.dll"
ProductName = "K2 basecamp"
ProductVersion = "0.7.1"
