[package]
name = "k2_basecamp"
version = "0.5.4"
authors = ["Christian Fochler <fochler@ehealhtexperts.de>"]
repository = "http://stash.ehex.de/scm/k2/k2-basecamp.git"
publish = false
build = "build.rs"

[lib]
name = "ctehxk2"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.4"
hyper = "0.10"
lazy_static = "0.2"
log = "0.3"
log4rs = "0.6"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[build-dependencies]
rusty-cheddar = "0.3"
