[package]
name = "k2_basecamp"
version = "0.14.9"
description = "CTAPI adpater for the gematik Konnektor"
authors = ["Christian Fochler <fochler@ehealhtexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-basecamp.git"
publish = false
build = "build.rs"

[lib]
name = "ctehxk2"
crate-type = ["cdylib"]

[dependencies]
antidote = "1.0.0"
base64 = "0.9.2"
futures = "0.1.23"
hyper = "0.11.27"
lazy_static = "1.0.1"
log = "0.4.3"
log4rs = "0.8.0"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.22"
tokio-core = "0.1.17"

[dependencies.config]
version = "0.9.0"
default-features = false
features = ["json", "toml", "yaml"]

[build-dependencies]
moz-cheddar = "0.4.2"

[dev-dependencies]
rand = "0.5.4"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "v0.2.1" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.6"

[package.metadata.winres]
FileDescription = "K2 adapter for CTAPI"
FileVersion = "0.14.9"
LegalCopyright = "eHealthExperts GmbH. All rights reserved."
OriginalFilename = "ctehxk2.dll"
ProductName = "K2 basecamp"
ProductVersion = "0.14.9"
