[package]
name = "k2_basecamp"
version = "0.15.4"
description = "CTAPI adpater for the gematik Konnektor"
authors = ["Christian Fochler <fochler@ehealhtexperts.de>"]
license = "MIT"
homepage = "http://k2.ehealthexperts.de"
repository = "https://github.com/eHealthExperts/k2-basecamp.git"
publish = false
build = "build.rs"

[lib]
name = "ctehxk2"
crate-type = ["cdylib"]

[dependencies]
antidote = "1.0.0"
base64 = "0.9.3"
lazy_static = "1.1.0"
log = "0.4.5"
log4rs = "0.8.0"
reqwest = "0.9.2"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.32"

[dependencies.config]
version = "0.9.1"
default-features = false
features = ["json", "toml", "yaml"]

[build-dependencies]
moz-cheddar = "0.4.2"

[dev-dependencies]
rand = "0.5.5"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "v0.5.3" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.6"

[package.metadata.winres]
FileDescription = "K2 adapter for CTAPI"
FileVersion = "0.15.4"
LegalCopyright = "eHealth Experts GmbH. All rights reserved."
OriginalFilename = "ctehxk2.dll"
ProductName = "K2 basecamp"
ProductVersion = "0.15.4"
