[env]
RUST_TEST_THREADS = "1"

[tasks.patch-version]
install_crate = "cargo-release"
command = "cargo"
args = ["release", "-l patch"]

[tasks.minor-version]
install_crate = "cargo-release"
command = "cargo"
args = ["release", "-l minor"]

[tasks.major-version]
install_crate = "cargo-release"
command = "cargo"
args = ["release", "-l major"]

[tasks.format]
description = "Runs the cargo rustfmt plugin."
install_crate = "rustfmt"
command = "rustup"
args = ["run", "nightly", "cargo", "fmt", "--all"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]
