[env]
RUST_TEST_THREADS = "1"

[tasks.patch-version]
install_crate = "cargo-release"
command = "cargo"
args = ["release", "--level", "patch"]

[tasks.minor-version]
install_crate = "cargo-release"
command = "cargo"
args = ["release", "--level", "minor"]

[tasks.major-version]
install_crate = "cargo-release"
command = "cargo"
args = ["release", "--level", "major"]

[tasks.format]
description = "Runs the cargo rustfmt plugin."
install_crate = "rustfmt"
command = "rustup"
args = ["run", "nightly", "cargo", "fmt", "--all"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean", "build"]
