[package]
name = "use-libray"
version = "0.1.0"

[dependencies]
const-cstr = "0.3.0"
dlopen = "0.1.4"
rand = "0.5.4"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "v0.2.1" }
