[package]
name = "use-libray"
version = "0.1.0"

[dependencies]
const-cstr = "0.2.1"
dlopen = "0.1.3"
rand = "0.4.2"
test-server = { git = "https://github.com/ChriFo/test-server-rs", tag = "v0.3.0" }
